### ISSUE TITLE
I would like to get real-time open prices So I am going to draw this plot

### ISSUE THREAD

**Issue by jiany30** [Jeffrey-Keyser/TD_Ameritrade_Stock#1]
I would like to get real-time open prices
So I am going to draw this plot
![Screenshot_1](https://user-images.githubusercontent.com/62179052/78970853-dcbf4c00-7b3c-11ea-8f49-d0650315284d.png)

But I can't get the prices now.
Can you help me?
Best regards!

**Comment by Jeffrey-Keyser** [comment]
I've benched this project for the moment, so I don't believe I can help. Sorry!
